apiVersion: v1
kind: Service

metadata:
  name: devops-master-service

spec:
  selector:
    app: devops-master-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP
